spring:
  shardingsphere:
    datasource:
      names: ds-master, ds-slave-1, ds-slave-2
      # 订单 orders 主库的数据源配置
      ds-master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://81.71.68.248/test_orders?useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root
      # 订单 orders 从库数据源配置
      ds-slave-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://81.71.68.248/test_orders_slave_01?useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root
      # 订单 orders 从库数据源配置
      ds-slave-2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://81.71.68.248/test_orders_slave_02?useSSL=false&autoReconnect=true&failOverReadOnly=false
        username: root
        password: root
    # 读写分离配置，对应 YamlMasterSlaveRuleConfiguration 配置类
    masterslave:
      name: ms
      master-data-source-name: ds-master
      slave-data-source-names: ds-slave-1, ds-slave-2
