spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_trigger?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  # 配置mapper.xml路径
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 配置别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  type-aliases-package: com.lizuoyang.springboot.entity
  global-config:
    #刷新mapper 调试神器
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
