spring:
  data:
    # MongoDB配置项
    mongodb:
      host: 81.71.68.248
      port: 27017
      database: testdb
#      username: user
#      password: 123456

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # 打印 mongodb 操作的具体语句。生产环境下，不建议开启。

